Create Energetics Meets Generex.md
Watts-Lab/task-mapping pull request #144
Opened 2021-06-07 18:34 UTC by sarikasu

2021-08-05 03:43 UTC, KaranSampath commented on tasks/Energetics Meets Generex.md
> +ASKED FOR MORE DETAILS 6/7.
Have we received any response?

2021-08-05 03:45 UTC, KaranSampath requested changes
We'll need to check if we can find any more in-depth instructions.

2021-08-05 03:56 UTC, KaranSampath commented on tasks/Energetics Meets Generex.md
> +ASKED FOR MORE DETAILS 6/7.
We'll also need to add details of the alternate studies.

2021-08-09 14:44 UTC, sarikasu reviewed
No instructions from researchers- they said to reference those on the negotiations website!

2021-08-11 21:12 UTC, KaranSampath approved these changes

2021-08-11 21:12 UTC, merged