Create Crisis Mapping
Watts-Lab/task-mapping pull request #185
Opened 2021-08-09 16:28 UTC by sarikasu

2021-08-14 16:35 UTC, sarikasu reviewed
removed alternative section

2021-08-18 15:25 UTC, KaranSampath commented on tasks/Crisis Mapping.md
> +Detailed Instructions with images: https://storage.googleapis.com/plos-corpus-prod/10.1371/journal.pone.0153048/1/pone.0153048.s006.pdf?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=wombat-sa%4
Link is broken, will need to be replaced.

2021-08-18 15:26 UTC, KaranSampath requested changes
Need to replace broken link

2021-08-21 23:52 UTC, sarikasu reviewed
updated link

2021-08-22 00:04 UTC, KaranSampath approved these changes

2021-08-22 00:04 UTC, merged