Create Word completion given part of word.md
Watts-Lab/task-mapping pull request #233
Opened 2021-09-15 18:23 UTC by sarikasu

2021-09-16 17:55 UTC, benjamin-manning requested changes

2021-09-16 17:55 UTC, benjamin-manning commented on tasks/Word completion given part of word.md
> +Main Paper: https://www.science.org/doi/abs/10.1126/science.1193147
```suggestion
Main Paper: https://www.science.org/doi/abs/10.1126/science.1193147

Task Source: McGrath, Joseph Edward. Groups: Interaction and performance. Vol. 14. Englewood Cliffs, NJ: Prentice-Hall, 1984. http://users.ece.utexas.edu/~perry/education/382v-s08/papers/mcgrath84.pdf
```

2021-09-16 17:55 UTC, benjamin-manning commented on tasks/Word completion given part of word.md
> +
```suggestion
4b. Other versions of the task use a different time period and different numbers of words, but the other features are the same. Additionally, this task comes from McGrath's broader set of tasks (quadrant 2 in his work) that are intellective: solving problems with a correct answer.
```

2021-09-16 17:55 UTC, benjamin-manning commented on tasks/Word completion given part of word.md
> +
```suggestion
Alternative task method: http://www.craiganderson.org/wp-content/uploads/caa/Scales/WordComp.pdf
```

2021-09-16 17:55 UTC, benjamin-manning commented on tasks/Word completion given part of word.md
> +
```suggestion
# Alternative Procedure
## Steps

1. Participants arrive and are told participants that they were looking at a list of 98 words with letters missing (varying in number), and that their task was to fill in the blanks to make complete words by themselves
2. Participants were given three minutes to complete as much of the word task as
they could. 
```

2021-09-16 17:55 UTC, benjamin-manning commented on tasks/Word completion given part of word.md
> +
```suggestion
Alternative:  Participant responses were coded into the following categories: aggressive words, neutral words, ambiguous words, and non-words.
```

2021-09-16 18:52 UTC, sarikasu reviewed
Stimuli not available from researchers I added some words!

2021-09-20 21:46 UTC, benjamin-manning approved these changes

2021-09-20 21:46 UTC, benjamin-manning commented on tasks/Word completion given part of word.md
> +ocean: _ _cean
```suggestion
ocean:  _ _can            
```

2021-09-20 21:46 UTC, benjamin-manning commented on tasks/Word completion given part of word.md
> +downtown: do_ _ _wn
```suggestion
downtown: dow_ _ _wn
```

2021-09-20 21:47 UTC, benjamin-manning approved these changes

2021-09-20 21:47 UTC, benjamin-manning commented on tasks/Word completion given part of word.md
> +garrulous: _ _rulous
```suggestion
garrulous: _ _ _rulous 
```

2021-09-20 21:47 UTC, merged