Create Conformity Game.md
Watts-Lab/task-mapping pull request #271
Opened 2021-10-15 17:01 UTC by paniukhina

2021-10-30 20:46 UTC, paniukhina commented on tasks/Conformity Game.md
> +## Instructions
Edited the sentence

2021-10-30 20:47 UTC, paniukhina commented on tasks/Conformity Game.md
> +All sessions took place in the Social Behavior Computer Laboratory at Florida Atlantic University, which at the time consisted of 12 personal computers linked in a Novell network. Participants were a
Made edits as suggested

2021-10-30 20:48 UTC, paniukhina commented on tasks/Conformity Game.md
> +Each participant recieved $1 for predicting each answer of the majority.
Added about the base payment but I did not fond how much they paid

2021-11-10 17:53 UTC, DodgeHill requested changes
small changes

2021-11-10 17:53 UTC, DodgeHill commented on tasks/Conformity Game.md
> +Each participant recieved a base payment, and then was paid $1 for predicting each answer of the majority.
Change to "Each participant received a base payment regardless of performance. Participants could then earn $1.00 each time they correctly predicted the majority answer.

2021-11-10 17:53 UTC, DodgeHill commented on tasks/Conformity Game.md
> +## Instructions
We still may have to make changes throughout this section so that we do not infringe on copyright

2021-11-10 18:36 UTC, DodgeHill commented on tasks/Conformity Game.md
> +## Instructions
Talked with Mark, it is okay as it

2021-11-10 18:37 UTC, DodgeHill requested changes

2021-11-10 18:37 UTC, DodgeHill commented on tasks/Conformity Game.md
> +Paper: https://psycnet.apa.org/fulltext/1996-01769-008.html#s7
Need to add a citation in here

2021-11-11 01:28 UTC, DodgeHill commented on tasks/Conformity Game.md
> +Paper: https://psycnet.apa.org/fulltext/1996-01769-008.html#s7
Latané, Bibb, and Todd L'Herrou. "Spatial clustering in the conformity game: Dynamic social impact in electronic groups." Journal of personality and social psychology 70.6 (1996): 1218.

2025-10-12 21:07 UTC, closed without merging